.github/workflows/bumpversion.yml, .github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/security.yml, .github/workflows/test.yml, src/twyn/dependency_parser/poetry_lock.py, tests/conftest.py, tests/dependency_parser/test_dependency_parser.py
We've been blocked by dparse library not being able to parse newest poetry lock versions, which was making our pipelines fail since we run twyn against our dependencies. We will consider completely dropping the usage of dparse, to make Twyn more lightweight.
Since we now require `tomllib`, which is present on Python versions 3.11 onwards, and this tool is now meant to be run standalone (meaning, not as a package), we're also dropping the tests against previous Python versions.
Also added some comments to the workflow files.
=> feat: Support poetry version format >= 1.5.0

src/twyn/core/exceptions.py, src/twyn/dependency_parser/abstract_parser.py, src/twyn/dependency_parser/dependency_selector.py, src/twyn/dependency_parser/exceptions.py, src/twyn/file_handler/exceptions.py, src/twyn/file_handler/file_handler.py, tests/conftest.py, tests/dependency_parser/test_dependency_parser.py, tests/dependency_parser/test_dependency_selector.py, tests/file_handler/test_file_handler.py
First MR towards having a cache file for saving the trusted packages into a file (#143).
Created a new class FileHandler, which will hold all the interactions towards reading/writing files. 
Adapted AbstractParser to use it.
In the following MRs:
- adapt ConfigHandler to also use it.
- save trusted packages to a file.
=> chore: Introduce FileHandler

src/twyn/cli.py, src/twyn/dependency_parser/dependency_selector.py, tests/conftest.py, tests/dependency_parser/test_dependency_selector.py, tests/main/test_cli.py, tests/main/test_main.py
Now Twyn  can load a file that is not in the root directory.
We still check for the name of the file, which has to be one of the supported ones (`poetry.lock` or `requirements.txt`).
This PR is for fixing the bug, but in the future Twyn should support any name in the file (i.e. `requirements-dev.txt`) #158.
=> fix: select file from paths that are not in the root folder

Dockerfile
The entrypoint of a docker image for a tool should be the tool entrypoint and contain no args.
Otherwise users cannot call other options (like `--help` or whatever).
Also moving to the latest supported version of Python.
Tested locally:
=> fix: move docker to python 3.13 and change entrypoint

src/twyn/core/config_handler.py, src/twyn/core/exceptions.py, src/twyn/main.py, tests/core/test_config_handler.py, tests/main/test_main.py
There are several problems (imo) with the `ConfigHandler` as it is:
- It keeps a lot of state internally, which makes it harder to reason about
- It reads files and does stuff on `init` which makes it harder to use in tests, it's a strange side effect to read files on init.
- It treats `tomlkit` as a `dict`, but `tomlkit` uses a `TOMLDocument` class (which acts _somehow_ as a dict, but is not entirely a `dict`).
- The handler was the config.
- The resolution of the config (deciding between cli/file/defaults) was done outside of the config handler.
In this PR:
- The handler is initialized and nothing happens yet.
- You can choose to `resolve_config(...)` and you get back a frozen dataclass with defaults and everything you need to run Twyn. Pass in any cli arguments you have, and …
=> refactor: rewrite configuration handler

README.md, src/twyn/base/constants.py, src/twyn/core/config_handler.py, src/twyn/main.py, src/twyn/trusted_packages/constants.py, src/twyn/trusted_packages/references.py, tests/core/test_config_handler.py, tests/main/test_main.py, tests/trusted_packages/test_references.py
Now you can configure the `pypi-reference` in your config file.
=> feat: configurable pypi-reference

src/twyn/base/exceptions.py, src/twyn/cli.py, src/twyn/config/config_handler.py, src/twyn/dependency_parser/abstract_parser.py, src/twyn/dependency_parser/dependency_selector.py, src/twyn/file_handler/file_handler.py, src/twyn/main.py, src/twyn/similarity/algorithm.py, src/twyn/trusted_packages/references.py, src/twyn/trusted_packages/selectors.py, tests/conftest.py, tests/main/test_cli.py
We were mixing two different concepts:
- `logging` are messages about what twyn is doing, etc. Using the logging module.
- `messages` are direct prints to the terminal by the cli
I changed it to be separated:
- The final "Typosquat detected" is now a `click` message. Not an "error" (it's not an _error_, the tool worked correctly!)
- Added a new "no typosquats detected", in green.
- Made the loggers named.
- Made all exceptions inherit from `ClickException`, as the click docs suggest.
- Made `TwynError` display tracebacks only on debug mode.
Examples:
- Typosquat detected
- No typosquat detected
- An error (an exception) raised with no "DEBUG" flag
- An error (an exception) raised with "DEBUG" flag
(as you can see in the last image, one nice perk of this is that we are taking advantage of …
=> fix(#167): Separate "messages" from "logging"

src/twyn/cli.py, src/twyn/config/config_handler.py, src/twyn/dependency_parser/abstract_parser.py, src/twyn/file_handler/file_handler.py, src/twyn/main.py, tests/core/test_config_handler.py, tests/file_handler/test_file_handler.py, tests/main/test_main.py
Integrate FileHandlerPathlib in ConfigHandler class.
That will make the file handler be the only one interacting with read/writes to disk. It can be seen as an additional layer, where some other parts of Twyn are built on.
This is another PR for #143.
=> chore: Use FileHandlerPathlib in ConfigHandler

.github/workflows/publish.yml, pyproject.toml
Release notes are created at the moment we publish tags. However, the fact that we could publish them does not mean that the `bump_version` job was successful, like in [this case](https://github.com/elementsinteractive/twyn/actions/runs/13197400016/job/36841617955), due to a misconfiguration of the rulesets. 
An easy way to solve the issue above would be: 1)fix the rulesets 2) delete tags 3) rerun `bump_version` job. That's not currently possible, because in order to delete the tags we would need to first delete the release notes, and even if we did this, the job that publishes the release notes will be called twice.
This PR ensures that we only publish the release notes if all the other jobs have succeeded, to avoid unexpected consequences.
=> ci: Trigger release notes job after publishing has succeeded

.github/workflows/security.yml
Right now it's pinned to `latest`. This is a problem as there's a breaking change in their newest image `v2.0.0-beta`.
I'm pinning the version in our workflow, and once there's an official `v2` we can move towards using it.
=> fix: pin osv's version to 1.9.2

LICENSE, pyproject.toml, uv.lock
Setuptools as of now does not create License files with the latest available version (24). This translates in the package not being able to be published to PyPi.
More info: https://github.com/astral-sh/uv/issues/9513
=> fix: replace setuptools with hatchling

src/twyn/base/constants.py
To stay within quota, it now has just under 30 days of data, so the filename has been updated. Both will be available for a while. See https://github.com/hugovk/top-pypi-packages/pull/46.
=> Update top-pypi-packages filename

Dockerfile
We've noticed a race condition when publishing the image to docker hub. Up until now we were downloading `twyn` from pypi to have it installed in our docker image. Turns out not always the latest available version was downloaded.
With this changes we are installing everything in the docker image directly from source.
=> fix: Change Dockerfile to install twyn directly from the source code

Dockerfile
By doing this we speed up the docker build, since we run ensurepip before copying the dependency files.
Without the `--inexact` flag the pip installation would be removed when running `uv sync`, as by default it deletes all packages not preset in the `uv.lock` file.
=> build: run ensurepip before copying lock dependency files

.github/actions/docker-build/action.yml, .github/workflows/build-test.yml, .github/workflows/publish.yml
This PR centralices all the needed actions to build and push the docker image. 
This is a convenience, so that we know that everything related to the build lies in this file, and if it gets updated (i.e because of a dependabot update) it will automatically run our `test-docker-build` from `build-test.yml.`
=> ci: Create action for docker builds

.github/workflows/conventional-label.yaml
This check was also running on forks, while it shouldn't
=> fix: run conventional-label only on main

src/twyn/__init__.py
This will help with development when `twyn` is used as a library.
=> feat: expose `check_dependencies` to the main interface

src/twyn/cli.py, src/twyn/main.py, tests/main/test_cli.py, tests/main/test_main.py
This PR adds the capability of disabling the track through the cli as well as from the public package interface.
When running twyn as a cli tool by default the track is shown, whereas while it's being used as a package it is disabled.
closes #281
=> feat: allow to disable track while evaluating dependencies

src/twyn/cli.py, src/twyn/main.py, src/twyn/trusted_packages/trusted_packages.py, tests/conftest.py, tests/main/test_cli.py, tests/main/test_main.py, tests/trusted_packages/test_trusted_packages.py
Introduces `--json` flag to return the results as a json.
It no longer uses click.echo, for some reason it is not captured in the output and it's impossible to test.
Another important addition here is that `check_dependencies` now returns an object of the new class `TyposquatCheckResultList`. This breaks previous implementations of those using `twyn` as a package.
It also renames `candidate_dependency` to `dependency` and `similar_results` to `similarities` from the `TyposquatCheckResult` model.
BREAKING CHANGE
closes #283
=> feat: allow to get results as json

README.md
=> docs: update docs with json and "twyn as a package" examples

README.md, src/twyn/cli.py, src/twyn/main.py, tests/conftest.py, tests/main/test_main.py
Typing was incorrect in `check_dependencies` function, where it was stated that `selector_method` was a mandatory argument, while it wasn't.
=> fix: Properly annotate `check_dependencies`'s `selector_method` arg

README.md, src/twyn/base/constants.py, src/twyn/cli.py, src/twyn/config/config_handler.py, src/twyn/file_handler/file_handler.py, src/twyn/main.py, tests/config/test_config_handler.py, tests/conftest.py
=> feat: load config from `twyn.toml` if it exists

.gitignore, README.md, src/twyn/base/constants.py, src/twyn/cli.py, src/twyn/config/config_handler.py, src/twyn/dependency_parser/dependency_selector.py, src/twyn/main.py, tests/config/test_config_handler.py, tests/conftest.py, tests/dependency_parser/test_dependency_selector.py, tests/main/test_cli.py, tests/main/test_main.py
With this PR we extend the functionality of parsing multiple files to also be able to auto locate them recursively, scanning subdirectories. Note that it will exclude `.git` directory to speed up the process.
closes #323
=> feat: recursively look for lock files

src/twyn/cli.py, src/twyn/config/config_handler.py, src/twyn/dependency_parser/dependency_selector.py, src/twyn/main.py, tests/config/test_config_handler.py, tests/conftest.py, tests/dependency_parser/test_dependency_selector.py, tests/main/conftest.py, tests/main/test_cli.py, tests/main/test_main.py
This PRs  allows the user to set multiple files both via the cli and the config file.
In a future PR we will validate the types of the config fields.
refs #325
=> feat: support multiple dependency files in config and cli

src/twyn/cli.py, src/twyn/config/config_handler.py, src/twyn/main.py, tests/main/test_cli.py, tests/main/test_main.py
Adds `--npm-source` and `--pypi-source` cli options.
closes #344
=> feat: allow to set ecosystem sources via the cli

Dockerfile
Small refactoring changes. We can now get rid of `--inexact`.
=> build: refactor Dockerfile
